# Generated by Django 5.2.1 on 2025-05-10 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(related_name='employees_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
