# Generated by Django 5.2.1 on 2025-05-10 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='employees',
        ),
        migrations.AddField(
            model_name='team',
            name='employee',
            field=models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
