# Generated by Django 5.2.1 on 2025-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
