# Generated by Django 5.2.1 on 2025-05-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_create_team', 'Can create Team (only Team leaders)'),)},
        ),
    ]
