# Generated by Django 5.2.1 on 2025-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_team_leader',
            field=models.BooleanField(),
        ),
    ]
